
ALTER TABLE public.blog_posts
  ADD COLUMN IF NOT EXISTS canonical_url TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS og_title TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS og_description TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS og_image TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS twitter_card TEXT NOT NULL DEFAULT 'summary_large_image',
  ADD COLUMN IF NOT EXISTS robots_index BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS robots_follow BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS image_alt TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS image_caption TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS related_posts UUID[] NOT NULL DEFAULT '{}';
